provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  test-branching:
    lang: faas-flow
    handler: ./test-branching
    image: test-branching:latest
    labels:
      faas-flow: 1
    annotations:
      faas-flow-desc: "flow for an example braching execution"
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      exec_timeout: 0
      combine_output: false
    environment_file:
      - flow.yml
    secrets:
      - s3-secret-key
      - s3-access-key
